### ISSUE TITLE
Add Array Type

### ISSUE THREAD

**Issue by zaporter** [sdumetz/node-wayland-client#2]
Hello!

While trying to use [wlr-foreign-toplevel-management-unstable](https://wayland.app/protocols/wlr-foreign-toplevel-management-unstable-v1), I ran into some trouble with the array types.

I thought this would be a simple PR. However, `wl_array` is pretty underspecified (can hold any type of any sizes in it at runtime).

[The rust wayland_client](https://docs.rs/wayland-client/latest/wayland_client/backend/protocol/enum.ArgumentType.html#variant.Array) just exports the `Array` as a `Vec<u8>` and forces users to parse out the array.

I added a `wl_array = number[]` type in this diff: https://github.com/zaporter/node-wayland-client/compare/zp/formatter...zaporter:node-wayland-client:zp/array?expand=1

It works locally and I can now use `wlr-foreign-toplevel-management`. However, this is pretty hacky because the `number` is being parsed as a 4 byte unsigned integer (instead of a byte array). 

---------

I am still very new to wayland and you seem to know it a lot better. Do you have any advice for how I should implement array?

My current thought was to implement some kind of `export parseArrayInto<T>(array: wl_array, definition: ArgumentDefinition): T[]` that end-users can call -- and then export `wl_array` as `Buffer`. But I haven't tested this to ensure it is possible.

**Comment by sdumetz** [comment]
I see what you mean: 
 > array: A blob of arbitrary data, prefixed with a 32-bit integer specifying its length (in bytes), then the verbatim contents of the array, padded to 32 bits with undefined data.

Ideally, shouldn't we return a properly-sized `UInt8Array` (or `Buffer`) ? [Making a slice view](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/buffer#accessing_the_underlying_buffer_from_a_sliced_array_view)


I think casting it  into something else is better left to the client because it's a standard problem (maybe better handled by TypedArrays than Buffers) and he knows more about the underlying data and how it should be handled than we do.

**Comment by zaporter** [comment]
@sdumetz

> Ideally, shouldn't we return a properly-sized UInt8Array (or Buffer) ?

Good point. `UInt8Array` seems more like what other libraries (and libwayland) do. I've thrown up a PR with this change.
